// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHCYmsIuw_MYKjhpJ6CUgRnIuV3QGeXog',
    appId: '1:551014826419:web:9bd14b1c39560ed43c4bc6',
    messagingSenderId: '551014826419',
    projectId: 'kt-notes-f4028',
    authDomain: 'kt-notes-f4028.firebaseapp.com',
    storageBucket: 'kt-notes-f4028.appspot.com',
    measurementId: 'G-FDKBHT0G7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYB54BhmT9xBGL2_4E7y2BvzbxK9r_I7w',
    appId: '1:551014826419:android:aafe0413f87c02843c4bc6',
    messagingSenderId: '551014826419',
    projectId: 'kt-notes-f4028',
    storageBucket: 'kt-notes-f4028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOmBJNQrEN2ExxG0_Q70tGMMl1XrwqbSQ',
    appId: '1:551014826419:ios:9b5fd8c50aa43efb3c4bc6',
    messagingSenderId: '551014826419',
    projectId: 'kt-notes-f4028',
    storageBucket: 'kt-notes-f4028.appspot.com',
    iosBundleId: 'com.ktdev.ktnotes',
  );
}
